<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-4QGIS7L0" ignored="0" name="MantenimientoProviderFirefox" tests="4" failures="4" timestamp="08 nov 2018 19:54:42 GMT" time="0.142" errors="0">
  <testcase name="editarCategoria_Criterio01" time="0.006" classname="pe.com.test.system.testCase.MantenimientoProvider">
    <failure type="java.lang.AssertionError" message="Error: null">
      <![CDATA[java.lang.AssertionError: Error: null
at pe.com.test.system.testCase.MantenimientoProvider.editarCategoria_Criterio01(MantenimientoProvider.java:181)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- editarCategoria_Criterio01 -->
  <testcase name="editarCategoria_Criterio02" time="0.002" classname="pe.com.test.system.testCase.MantenimientoProvider">
    <failure type="java.lang.AssertionError" message="Error: null">
      <![CDATA[java.lang.AssertionError: Error: null
at pe.com.test.system.testCase.MantenimientoProvider.editarCategoria_Criterio02(MantenimientoProvider.java:204)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- editarCategoria_Criterio02 -->
  <testcase name="insertarCategoria_Criterio01" time="0.002" classname="pe.com.test.system.testCase.MantenimientoProvider">
    <failure type="java.lang.AssertionError" message="Error: null">
      <![CDATA[java.lang.AssertionError: Error: null
at pe.com.test.system.testCase.MantenimientoProvider.insertarCategoria_Criterio01(MantenimientoProvider.java:135)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- insertarCategoria_Criterio01 -->
  <testcase name="insertarCategoria_Criterio02" time="0.001" classname="pe.com.test.system.testCase.MantenimientoProvider">
    <failure type="java.lang.AssertionError" message="Error: null">
      <![CDATA[java.lang.AssertionError: Error: null
at pe.com.test.system.testCase.MantenimientoProvider.insertarCategoria_Criterio02(MantenimientoProvider.java:158)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- insertarCategoria_Criterio02 -->
</testsuite> <!-- MantenimientoProviderFirefox -->
